### PR TITLE
GPA-7871: Updated Regular Font

### PR DESCRIPTION
**Pull request by stasis2015**
Updating the PDF library revealed an issue with the Regular font.  I went ahead and grabbed an updated version of the Roboto library (which had alot more Lookups in it) and added back our glyphs and that fixed the issue.
Not sure what happened to our font along the way but this font definitely prints nicer in the pdfs
Here is the glyphs I added back (I went through the pull requests - hopefully I didn't miss one)
Big X			uni2715	
Composition		uni25E6	
Angle			uni2220	
Triangle_Symbol		uni25B3	
Square			uni25A1	
Congruent		uni2245	
Left_Ceiling_Bracket	uni23BE	
Left_Floor_Bracket	uni23BF	
Right_Celing_Bracket	uni23CB	
Right_Floor_Bracket	uni23CC	
Right_Arrow		uni279C	
Union			uni222A	
Intersection		uni2229	
Bullet_Dot		uni26AB	
Black Circle		uni25CF	
Black Large Circle	uni2B24
circle   uni2218

### CODE REVIEW

**Comment by bblocher** [comment]
Let's us a font comparison tool to ensure all glyphs are present. Additionally we can determine why this font is so much larger and reduce it.

**Comment by stasis2015** [comment]
Good call on the diff tool, turned out I was missing uni2218.  I used fontdiffenator (looks like we aren't the only ones with great naming of tools) https://github.com/googlefonts/fontdiffenator
Here is the summary of the results (keep in mind I updated the font to use the latest repo)
[Summary.txt](https://github.com/frontporch/roboto-gmm/files/9735901/Summary.txt)

Here is the gifs it spit out:
[result_gifs.zip](https://github.com/frontporch/roboto-gmm/files/9735910/result_gifs.zip)

**Comment by stasis2015** [comment]
One more note - in the summary it is stating a missing glyph is `Tcommaaccent` but it is in this version of the font.  Here is a screenshot:
not-missing

**Comment by stasis2015** [comment]
Here is the results from the base Roboto font compiled vs this font
[Summary.txt](https://github.com/frontporch/roboto-gmm/files/9747987/Summary.txt)

Along with the gifs:
[gifs-roboto-gmm.zip](https://github.com/frontporch/roboto-gmm/files/9747990/gifs-roboto-gmm.zip)

**Comment by stasis2015** [comment]
Here is the results for Roboto published in Google Fonts vs ours;
[Summary.txt](https://github.com/frontporch/roboto-gmm/files/9748215/Summary.txt)

Along with the gifs:
[gifs.zip](https://github.com/frontporch/roboto-gmm/files/9748216/gifs.zip)

**Comment by stasis2015** [comment]
There has been alot more glyphs added `glyphs new: 2119`

**Comment by stasis2015** [comment]
Although now I am wondering how we went from `381 KB`   to `523 KB` by pulling in the latest version of Roboto - I may need to look into this some more

**Comment by stasis2015** [comment]
Well I know why it is `523 KB` now.  When I pulled down the public repo instead of setting up the whole build process (which is quite a nightmare) I opted to go with their pre-compiled ttf files under the src/hinted folder and that is already at `504 KB`, so if we want this file down to the 300 range I will need to work on building it again with their process and then convert that one over again.

**Comment by stasis2015** [comment]
The font was most likely messed up because getting the roboto source to build on a Windows box is a horrible nightmare - outdated 3rd party dependencies and still using python 2.7.  I have spent a couple hours on this and am still coming up with errors.  I am not sure how much time we want to spend on this

**Review by bblocher — APPROVED** [review]

**Pull request merged**
