### PR TITLE
GPA-7880: Rework Regular Font

### PR DESCRIPTION
**Pull request by stasis2015**
This task was originally to get the roboto repo to build, which I did. I discovered that it still had the same issues as our old font.
The latest font was pulled from an included font in the repo but I just read that it didn't even use the repo source but is being used as a temporary font for different devices until they can get the source font decent enough.
I also discovered that this font was a bit higher than our's, so I grabbed the old .sfd and made the some adjustements to widths and kerning of different characters.  I think it is at a pretty good place but you might want to check it out yourself.
Good news though, I ran it against the retro run and there were no failures, meaning that all the failures we have now are because of the latest font height change.

### CODE REVIEW

**Comment by stasis2015** [comment]
Also the font size is back to 382 KB

**Comment by stasis2015** [comment]
I made some final adjustments.
Here is a zip file with the pdf printouts of the numbers in the spacing ticket:
[adjusted-spacing-problems.zip](https://github.com/frontporch/roboto-gmm/files/9814521/adjusted-spacing-problems.zip)

**Comment by bblocher** [comment]
Still seeing the large gaps after t. Not sure if they kern values aren't large enough or not taking affect. Did you try excessive numbers to ensure they are being honored?

**Comment by stasis2015** [comment]
I have learned this is not the way to go
We should revert back to the old font before any changes
Switching the font size to 12 causes issues with text smashing into Values.
tagging Do Not Merge until we figure what is happening

**Comment by stasis2015** [comment]
We found a solution that involves no changes to the current font .. closing the pull request and deleting the branch

**Pull request closed without merging**
